spring.application.name=ecomm-distributed-hadoop
server.port=8081

# Hadoop HDFS
hdfs.namenode.url=hdfs://localhost:9000
hdfs.replication=2
hdfs.base.path=/ecomm

# ZooKeeper
zookeeper.address=localhost:2181
zookeeper.timeout=5000
